config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :products

  root 'projects#index'

  get 'export_projects', to: 'projects#export_projects'
  get 'export_products', to: 'projects#export_products'
  get 'import_product_list', to: 'products#import_products'
  get 'import_projects', to: 'projects#import'
  post 'project_import', to: 'projects#project_import'

end

app/models/project.rb
class Project < ApplicationRecord
    require 'csv'
    require 'zip'
    require 'rubygems'
    include Rails.application.routes.url_helpers

    has_one_attached :main_image
    has_many_attached :step_images
    belongs_to :language

    before_create :add_template_url, :add_country_to_id, :format_instructions, :format_skus, :save_main_image_link, :save_step_images, :format_youtube

    validates :main_image, content_type: ['image/png', 'image/jpg', 'image/jpeg']
                                                        # dimension: { width: { min: 800, max: 1000 },
                                                        #             height: { min: 600, max: 1000 }}
                                                                    
    validates :step_images, content_type: ['image/png', 'image/jpg', 'image/jpeg']
                                    #  dimension: { width: { min: 800, max: 1000 },
                                    #               height: { min: 600, max: 1000 }, message: 'is not given between dimension' }

    validates :uniqueid, uniqueness: true
    
    def add_template_url
        if self.template.present?
            self.template = "https://www.bakerross.co.uk/patticrafts/" + self.template
        end
    end

    def format_youtube
        if self.youtube.present?
            self.youtube = "https://www.youtube.com/embed/" + self.youtube
        end
    end

    
    def add_country_to_id
        if !self.uniqueid.include?("_#{self.language.code}")
            self.uniqueid = self.uniqueid + "_#{self.language.code}"
        end
    end
    
    def format_instructions
        if self.how_to_make.present?
            instructions = self.format_list(self.how_to_make, "ordered","\n")
            self.how_to_make = instructions
        end
    end

    def format_skus
        if self.products.present?
            skulist = self.products.split(",")
            shoppinglist=[]
            skulist.each do |item|
                product = Product.find_by_sku(item) 
                if product
                        shoppinglist.push("<a href=\"#{product.url}\">#{product.title}</a>")
                end
            end
        end

        if self.what_youll_need.present?
            shoppinglist = shoppinglist.join(",") 
            shoppinglist += "," + self.what_youll_need
            self.add_what_youll_need
        end

        if shoppinglist.present?
            self.shopping_list = self.format_list(shoppinglist ,"unordered",",") 
        end   
    end

    def add_what_youll_need
        wyn = self.format_list(self.what_youll_need,"unordered",",")
        self.what_youll_need = wyn
    end

    def format_list(list, option,char)
        final_list = list.split(char)
        outcome = ""
        if option == "ordered" 
            outcome += "<ol>"
        elsif option == "unordered"
            outcome += "<ul>"
        end

        final_list.each do |item|
            item = "<li>"+ item + "</li>"
            outcome += item
        end

        if option == "ordered" 
            outcome += "</ol>"
        elsif option == "unordered"
            outcome += "</ul>"
        end

        return outcome
    end

    def save_main_image_link
        if self.main_image.attached?
            self.mainimage = self.main_image.filename.to_s
        end
    end

    def save_step_images
        if self.step_images.attached?
                if !self.step_images[0].filename.to_s.empty?
                    self.image1 = self.step_images[0].filename.to_s
                end
                if !self.step_images[1].filename.to_s.empty?
                    self.image2 = self.step_images[1].filename.to_s
                end
                if !self.step_images[2].filename.to_s.empty?
                    self.image3 = self.step_images[2].filename.to_s
                end
        end
    end

    def self.search(search)
        puts search
        if search
            searchterm = search["search"]
            productfilter = search["noproducts"]
        end
        if searchterm && productfilter.nil?
            project = Project.where("LOWER(title) LIKE LOWER(?)", "%#{search["search"]}%")
        elsif productfilter == "1" && searchterm.empty?
            project = Project.where(products: nil)
        elsif productfilter == "1" && searchterm
            project = Project.where("LOWER(title) LIKE LOWER(?)", "%#{search["search"]}%").where(products:nil)
        else
            Project.all
        end    
    end

    def self.to_project_csv
        attributes = %w(uniqueid title intro mainimage image1 image2 image3 level time how_to_make shopping_list youtube what_youll_need tip template tags supervision products categories)
        headers = %w(uniqueid title intro mainimage image1 image2 image3 level time how_to_make shopping_list youtube what_youll_need tip template tags supervision products categories language)
        # byebug
        CSV.generate(headers: true) do |csv|
          csv << headers
    
          all.each do |project|
            data = attributes.map{ |attr| project.send(attr) }
            # byebug
            data << project.language.code 
            csv <<  data
            # byebug
          end
        end
    end

    def self.to_product_csv
        attributes = %w(uniqueid title products core_products)
    
        CSV.generate(headers: true) do |csv|
          csv << attributes
    
          all.each do |project|
            if project.products.present?
                csv << attributes.map{ |attr| project.send(attr) }
            end
          end
        end
    end

    def self.import_projects (csv)
        csv_text = File.read(csv)
        parsed_text = CSV.parse(csv_text, :headers => true)
        parsed_text.each do |row|
            p = Project.new
            p.title = row[0]
            p.uniqueid = row['uniqueid']
            p.language = Language.first
            p.save
        end
    end

  

    
    # def send_to_wordpress
    #     url = 'http://bakerross-wp.thepixel.host/creative-station/wp-json/wp/v2/media'
    #     username = Rails.application.credentials.dig(:wordpress, :user) 
    #     password = Rails.application.credentials.dig(:wordpress, :password) 
    #     conn = Faraday.new(
    #         url: "#{url}"
    #         headers: {
    #             'Content-Disposition' => 'form-data; filename="example.jpg"'
    #             'Content-Type' => 'image/jpeg'
    #         }
    #     ) do |f|
    #         f.request :multipart
    #         f.request :url_encoded
    #     end
    #     conn.basic_auth(ActiveSupport::Base64.encode64(username)},ActiveSupport::Base64.encode64(password))
    #     mi = Faraday::UploadIO.new(url_for(self.main_image),"image/jpeg")
    #     payload = {:file => file}
    #     conn.post('/', payload)
    # end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
 
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.search(params[:search])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  def import
    

  def project_import
    uploaded_file = params[:project_csv]
    Project.import_projects(uploaded_file)
    redirect_to projects_url
  end
  end

  def export_projects
    
    @projects = Project.where(created_at:(Export.last.created_at)...Time.now)
    # @projects = Project.all
    send_data @projects.to_project_csv, filename: "projects-#{Date.today}.csv" , disposition: "attachment", type: "text/csv"
    # download_images(@projects)
    Export.create
    # redirect_to action: "index" and return 
  end

  def export_products
    # redirect_to :index
    @projects = Project.all
    send_data @projects.to_product_csv, filename: "product-#{Date.today}.csv", disposition: "attachment", type: "text/csv"
    
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    # @project = Project.new(project_params)
    # @project.template = "www.bakerross.co.uk/patticrafts/" + @project.template

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:search, :noproducts, :title,:uniqueid,:intro, :main_image,:template, :supervision, :products, :core_products, :categories, :level,:time,:how_to_make, :what_youll_need, :tip,:tags, :language_id, :youtube, :project_csv, step_images:[])
    end

    
  def download_images(projects)
    tmp_project_folder = "tmp/archive_#{Date.today.to_s}"
      projects.each do |project|
          directory_length_same_as_images = Dir["#{tmp_project_folder}/*"].length == (project.step_images.length)
          step = project.step_images 
          FileUtils.mkdir_p(tmp_project_folder) unless Dir.exists?(tmp_project_folder) 
          step.each do |step_image|
              step_filename = step_image.filename.to_s
              create_tmp_folder_and_store_documents(step_image,tmp_project_folder,step_filename) unless directory_length_same_as_images
              create_zip_from_tmp_folder(tmp_project_folder, step_filename) unless directory_length_same_as_images
          end
          mainimagefilename = project.main_image.filename.to_s
          create_tmp_folder_and_store_documents(project.main_image,tmp_project_folder,mainimagefilename) 
          create_zip_from_tmp_folder(tmp_project_folder, mainimagefilename) 
          send_file(Rails.root.join("#{tmp_project_folder}.zip"), :type => 'application/zip', :filename => "Files.zip", :disposition => 'attachment')
      end
      
  end

  def create_tmp_folder_and_store_documents(document, tmp_project_folder, filename)
      File.open(File.join(tmp_project_folder, filename), 'wb') do |file|
       document.download { |chunk| file.write(chunk) }
      end
    end
    
  def create_zip_from_tmp_folder(tmp_project_folder, filename)
      Zip::File.open("#{tmp_project_folder}.zip", Zip::File::CREATE) do |zf|
        zf.add(filename, "#{tmp_project_folder}/#{filename}")
      end
  end

      
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.haml
.container

    = link_to image_tag("default-creative-station.jpg", class: "mx-auto pt-4 d-block"), root_path
    %h1{:class => "display-4 mx-auto py-4"} Edit associated Products
    = form_for @project, url: {action:"update"} do |f|

        %table{:class => "w-100", :style => "border-collapse:separate; border-spacing:0 1rem"}
            %tr{:class => "form-group"}
                %td
                    %h6 Title
                %td 
                    = f.text_field :title, :class => "form-control", :readonly => true 
            %tr{:class => "form-group"}
                %td
                    %h6 Unique Product ID
                %td
                    = f.text_field :uniqueid, :class => "form-control", :readonly => true         
            %tr{:class => "form-group "}
                %td
                    %h6 Core Products (SKUs)
                %td
                    = f.text_field :core_products, :class => "form-control", placeholder: "Essential product. Will hide shopping cart if out of stock. Separate by comma (no spaces)"   
            %tr{:class => "form-group"}
                %td
                    %h6 
                        Products (SKUs)
                        %span{ :style => "color: red"} &#x2a;
                %td
                    = f.text_field :products, :class => "form-control", placeholder: "All other BR products. Separate by comma (no spaces)"           
      
            %tr{:class => "form-group"}
                %td
                %td
                    = f.submit "Save", class: "btn btn-primary" 


    = link_to 'Back', projects_path, :class => "text-primary h5" 

app/views/projects/import.html.haml
.container

  = image_tag("default-creative-station.jpg", class: "mx-auto pt-4 d-block")
  
  %h1{:class => "display-4 mx-auto py-4"} Project Upload

  = form_with url: project_import_url do |f|
    %table{:class => "w-100", :style => "border-collapse:separate; border-spacing:0 1rem"}
      %tr{:class => "form-group"}
        %td
          %h6 Project File
        %td 
          = f.file_field :project_csv, class: "form-control-file"
      %tr
        %td  
      %tr{:class => "form-group"}
        %td
        %td
          = f.submit "Save", class: "btn btn-primary" 

  %br
  %br
  = link_to 'All projects', projects_path, :class => "text-primary h5"   

app/views/projects/index.html.erb
<div class="container">

<div class="mx-auto"> 
  <%= link_to image_tag("default-creative-station.jpg", class: "mx-auto my-4 d-block"), root_path%>
</div>
<h1 class="display-4 mb-4 mx-auto text-center">All Projects</h1>




<div class="dropdown mb-3">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Web Team Actions
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= link_to 'Upload new product data', products_path, :class => "dropdown-item" %>
    <%=link_to(export_projects_url, :class => "dropdown-item",  target: :_blank, :onclick => 'window.location.reload();') do%>
    Export projects 
          <% if !Project.all.empty? && !Export.all.empty?%>
            <span class="badge badge-primary badge-pill">
              <%=(Project.where(created_at:(Export.last.created_at)...Time.now).count) %>
            </span>
          <%end%>
        <% end%>
    <%= link_to 'Export products', export_products_url, :class => "dropdown-item",  target: :_blank%>
  </div>
</div>     
<%= link_to 'Add a new project', new_project_path, class: "text-info h3 float-left"%>
<div class="mb-3 float-right">
  <%= form_tag(projects_path, method: :get) do %>
    <%= text_field_tag("search[search]")%>
    <%= check_box_tag('search[noproducts]')%>
     <%= label_tag :noproducts, "Show Only Projects without Products" %>
    <%= submit_tag ("Search")%> 
  <% end %> 
</div>
<br>
<br>
<table class="table table-striped">
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <th scope="row"><%= link_to project.title, project %></th>
        <td class="text-info"><% if project.products.present?%>
            <%= "Has Products"%>
            <% end %>
        <td><%= link_to 'Edit products', edit_project_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'All Projects', projects_path, class: "text-primary h5" %>

</div>

app/views/projects/new.html.haml
.container

    = link_to image_tag("default-creative-station.jpg", class: "mx-auto pt-4 d-block"), root_path
    
    %h1{:class => "display-4 mx-auto py-4"} New Project


    = form_for @project, url: {action:"create"} do |f|

        %table{:class => "w-100", :style => "border-collapse:separate; border-spacing:0 1rem"}
            %tr{:class => "form-group pb-5"}
                %td
                    %h6 
                        Title 
                        %span{ :style => "color: red"} &#x2a;
                %td 
                    = f.text_field :title, :class => "form-control" 
            %tr
                %td
                    %h6 
                        Unique Product ID
                        %span{ :style => "color: red"} &#x2a;
                %td
                    = f.text_field :uniqueid, :class => "form-control", placeholder: "Don't include language code (ie: _en)"   
            %tr
                %td
                    %h6 
                        Categories
                        %span{ :style => "color: red"} &#x2a;
                %td
                    = f.text_field :categories, placeholder: "Separate by comma (no spaces)", :class => "form-control"  
            %tr
                %td
                    %h6 Tags
                %td
                    = f.text_field :tags, placeholder: "Separate by comma (no spaces)", :class => "form-control"                         
            %tr
                %td{:class => "form-group"}
                    %h6 Language
                %td
                    = f.collection_select(:language_id, Language.all, :id, :name, {}, {:class => "form-control"})            
            %tr
                %td
                    %h6 
                        Intro
                        %span{ :style => "color: red"} &#x2a;
                %td
                    = f.text_field :intro, :class => "form-control" 
            %tr

                %td{:class => "form-group"}
                    %h6 
                        Main Image
                        %span{ :style => "color: red"} &#x2a;
                %td
                    = f.file_field :main_image, :class => "form-control-file"
            %tr
                %td{:class => "form-group"}
                    %h6 
                        Step Images
                        %span{ :style => "color: red"} &#x2a;
                %td
                    = f.file_field :step_images, multiple: true, :class => "form-control-file"     
            %tr
                %td{:class => "form-group"}
                    %h6 Youtube Link
                %td
                    = f.text_field :youtube, placeholder: "Link string only (ie: rBRK19YtKFk)", :class => "form-control"      
            %tr
                %td
                    %h6 Level
                %td
                    = f.text_field :level, :class => "form-control"       
            %tr
                %td
                    %h6 Time
                %td
                    = f.text_field :time, :class => "form-control"       
            %tr{:class => "form-group"}
                %td
                    %h6 How to Make
                %td
                    = f.text_area :how_to_make, placeholder: "Separate by new line", :class => "form-control"      
            %tr{:class => "form-group"}
                %td
                    %h6 What You'll Need
                    (non BR items)
                %td
                    = f.text_field :what_youll_need, placeholder: "Separate by comma (no spaces)", :class => "form-control"      
            %tr
                %td
                    %h6 Tip
                %td
                    = f.text_field :tip, :class => "form-control"  
            %tr{:class => "form-group"}
                %td
                    %h6 Supervision
                %td{:class => "form-check form-check-inline"}
                    = f.radio_button :supervision, "yes", :class => "form-check-input"
                    = f.label :supervision_yes, "Yes", :class => "form-check-label mr-5"    
                    = f.radio_button :supervision, "no", :class => "form-check-input"
                    = f.label :supervision_no, "No", :class => "form-check-label"     
            %tr
                %td
                    %h6 Template
                %td
                    = f.text_field :template, placeholder: "Filename (including extension i.e .pdf)", :class => "form-control"            
            %tr
                %td
                    %h6 Products
                %td
                    = f.text_field :products, placeholder: "SKUs only. Separate by comma (no spaces)", :class => "form-control"             
            %tr
                %td
                    %h6 Core Products
                %td
                    = f.text_field :core_products,placeholder: "SKUs only. Separate by comma (no spaces)", :class => "form-control"             
            %tr
                %td
                    
                %td
                    = f.submit "Create", class: "btn btn-primary" 

    = link_to 'Back', projects_path, :class => "text-primary h5" 

app/views/projects/sho2w.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/show.html.haml
.container

   = image_tag("default-creative-station.jpg", class: "mx-auto pt-4 d-block")
   %h1{:class => "display-4 mx-auto py-4"}
      = @project.title
      %small{:class => "text-muted"}
         = @project.uniqueid
  
   %p 
      %h4 Intro: 
      = @project.intro
   %p 
      %h4 Language: 
      = @project.language.name
   %p
      %h4 Categories:
      - if @project.categories
         - @project.categories.split(",").each do |c| 
            = c
            %br
   %p
      %h4 Tags:
      - if @project.tags
         - @project.tags.split(",").each do |t| 
            = t
            %br
   %p 
      %h4 How to Make:   
      != @project.how_to_make 
   %p 
      %h4 Tip:   
      = @project.tip 
   %p
      %h4 Shopping List:   
      != @project.shopping_list
   %p 
      %h4 What You'll Need:
      != @project.what_youll_need
   %p 
      %h4 Level:
      = @project.level
   %p 
      %h4 Time:
      = @project.time
   %p 
      %h4 Main Image:
      %p   
         = @project.mainimage
      - if @project.mainimage
         = image_tag(@project.main_image, width: 400)
      
   %p 
      %h4 Step Images:
      %p
         = @project.image1
      %p   
         = @project.image2
      %p   
         = @project.image3   
   - @project.step_images.each do |img|
      %p
         = image_tag(img, width:300)
     
   %p
      = link_to 'Edit Products', edit_project_path(@project), class: "text-primary h5"
   %p
      = link_to 'Back', projects_path, class: "text-primary h5"